### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by rsuzuki0** [LPBeaulieu/Notebook-Maker-PrintANotebook#1]
When I try to run the script, I get this error:

> Traceback (most recent call last):
>   File "/Users/RS/BULK/HandwritingOCR/NotebookPages/Notebook-Maker-PrintANotebook-main/printanotebook.py", line 1108, in <module>
>     image_grayscale = ImageOps.grayscale(image)
>                                          ^^^^^
> NameError: name 'image' is not defined. Did you mean: 'Image'?

I run:
python3 printanotebook.py "title:my title" "author:me" "number_of_pages:20" "page_numbers" "heading_text_right:Date:                " "scriptreader:0.3:5:1:2:0.75" "toc_pages_spacing:26" "inches_per_ream_500_pages:2"

**Comment by LPBeaulieu** [comment]
All fixed! Thanks for the heads up and let me know if you find other issues!

**Comment by TomJansen** [comment]
When I try to run this exact code, I get this error:
"Traceback (most recent call last):
  File "/home/tom/Documents/Programming/Notebook-Maker-PrintANotebook/printanotebook.py", line 2518, in <module>
    blank_canvas_editable.rectangle([(3300/2-gutter_margin_width_pixels-
  File "/home/tom/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 316, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: x1 must be greater than or equal to x0"

**Comment by LPBeaulieu** [comment]
It should work now, thanks for the heads up! Let me know if there are other problems!
